replicaCount: 1

image:
  repository: jetbrains/teamcity-agent
  tag: "latest"
  pullPolicy: IfNotPresent

# must create a sealed secret named "teamcity-agent-secret" with the following keys:
# - token
tokenSecretName: "teamcity-agent-secret"


serverUrl: "XXXXXXXXXXXXXXX"
agentToken: "XXXXXXXXXXXXXXX"
agentName: "NAME-OF-AGENT"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"