replicaCount: 1

image:
  repository: jetbrains/teamcity-agent
  tag: "latest"
  pullPolicy: IfNotPresent

# if you want to use a secret to store your TeamCity server URL and agent token, provide the secret name here
# create a secret with the stringData containing your TeamCity server URL and agent token
serverUrlSecretName: "teamcity-server-url-secret"
agentTokenSecretName: "teamcity-agent-token-secret"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"